### ISSUE TITLE
Adding the CS50 course under Courses and Certifications

### ISSUE THREAD

**Issue by MarianaSouza** [MarianaSouza/web-dev-path#12]
Considering that it's important to learn how to think algorithmically to solve problems, we need to add the [CS50 course link](https://www.edx.org/course/cs50s-introduction-to-computer-science) under Courses and Certifications.

**Comment by MarianaSouza** [comment]
TIP: When submitting a Pull Request to solve an issue, mention the issue number on the PR so that they both get linked.
You can use something like "Solves #12" or "Referent to the issue #12".

**Comment by ZahraB21** [comment]
Should we close this issue?

**Comment by MarianaSouza** [comment]
> It seems its done. Should we close this issue?

Yes, please! Since we didn't use "Closes" on the PR, we have to come here to close it manually. Thanks, @ZahraB21 !

**Comment by ZahraB21** [comment]
Great. It is now closed.
