### ISSUE TITLE
Fixing the WordPress section

### ISSUE THREAD

**Issue by MarianaSouza** [MarianaSouza/web-dev-path#20]
We need to fix the WordPress section by organizing the links into item lists, such as we see in the HTML/CSS section:

![fixing-wordpress-section](https://user-images.githubusercontent.com/20016897/99002440-421f5500-24f1-11eb-9bb2-37993bd2ee3d.png)

_HOT TIP: When submitting a Pull Request to solve an issue, mention the issue number on the PR description (not on the title) so that they both get linked.
You can use something like "Solves #20" or "Closes #20"._

**Comment by ZahraB21** [comment]
I will fix this issue

**Comment by MarianaSouza** [comment]
> I will fix this issue

Lovely! Thanks, @ZahraB21 ! You can assign it to yourself on "Assignees" as we do with the PR's ;)

**Comment by ZahraB21** [comment]
Fixed the issue with Wordpress links and the pull request is merged.
