### ISSUE TITLE
Adding a section about putting a website online: domain, hosting, and DNS

### ISSUE THREAD

**Issue by MarianaSouza** [MarianaSouza/web-dev-path#21]
We need to create a session called "Launching a website".
We could start adding this tutorial from freeCodeCamp:

*  [How to Put a Website Online: Template, Coding, Domain, Hosting, and DNS](https://www.youtube.com/watch?v=NQP89ish9t8&feature=youtu.be)

**HOT TIP:**
_When submitting a Pull Request to solve an issue, mention the issue number on the PR description (not on the title) so that they both get linked.
You can use something like "Solves #21", "Referent to the issue #21", or Closes #21. By using Closes and the issue number, GitHub will automatically close the issue when the PR that is addressing it is merged into the master._

**Comment by ZahraB21** [comment]
I will do this once the other PR's are approved and merged to the master to avoid conflicts.

**Comment by ZahraB21** [comment]
This section has been added and the issue will now be closed.
