### ISSUE TITLE
Add some React courses under the JavaScript section

### ISSUE THREAD

**Issue by MarianaSouza** [MarianaSouza/web-dev-path#26]
We need to add some React course links under the JavaScript section.

_HOT TIP:
When submitting a Pull Request to solve an issue, mention the issue number on the PR description (not on the title) so that they both get linked.
You can use something like "Solves #26", "Referent to the issue #26", or Closes #26. By using Closes and the issue number, GitHub will automatically close the issue when the PR that is addressing it is merged into the master._

**Comment by ZahraB21** [comment]
@MarianaSouza, Would this [React Handbook for Beginners](https://www.freecodecamp.org/news/react-beginner-handbook/) be a good starting point? 

Also would you want it under JS or as a separate section?

**Comment by CarolDill** [comment]
Hi @ZahraB21 this one I think is good!! Maybe we could add [React Functional Components, Props, and JSX – React.js Tutorial for Beginners](https://www.freecodecamp.org/news/react-components-jsx-props-for-beginners/) too?

**Comment by ZahraB21** [comment]
@CarolDill Sure. I will add that too. Thanks.

**Comment by MarianaSouza** [comment]
> @MarianaSouza, Would this [React Handbook for Beginners](https://www.freecodecamp.org/news/react-beginner-handbook/) be a good starting point?
> 
> Also would you want it under JS or as a separate section?

That tutorial is a great starting point, @ZahraB21 ! Thanks for that!
Yeah, I'm not so sure about placing React inside the JS section either... Although React is a JS library, there is so much specific content. What do you think if, inside the JS section we create a bolded subtitle for JavaScript (vanilla) with the current tutorials and a new one with a bolded subtitle for React content?

**Comment by ZahraB21** [comment]
@MarianaSouza I like the idea. What if we kept the JS as what it is, then created a subtitle called JS Frameworks and then place the React inside the JS Frameworks? Then if we need to add other JS frameworks, it would go under the JS frameworks? 
Please let me know what you think. Thanks.

**Comment by MarianaSouza** [comment]
> @MarianaSouza I like the idea. What if we kept the JS as what it is, then created a subtitle called JS Frameworks and then place the React inside the JS Frameworks? Then if we need to add other JS frameworks, it would go under the JS frameworks?
> Please let me know what you think. Thanks.

Much better idea, @ZahraB21 ! I'd call that new section JS Libraries and Frameworks since React is a library, but we can also add Vue.js soon there ;)

**Comment by ZahraB21** [comment]
The JS Libraries and Frameworks along with React section is now merged with master branch. I will now close the issue.
