### ISSUE TITLE
Adding a Header Image to the repository

### ISSUE THREAD

**Issue by MarianaSouza** [MarianaSouza/web-dev-path#27]
I've created a simple logo for our Slack channel this week and also this wider one (attached) that I think we could add to the top of our repo as a header before the main h1 title, what do you think? I've already added a similar image (a narrower version) to our [social media preview](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-your-repositorys-social-media-preview) so that when we share the repo link, we see something more customized.

To do so, we would have to save this attached image into our images-web-dev-path folder and, then, add some HTML and inline CSS as described here: https://stackoverflow.com/questions/12090472/github-readme-md-center-image. If you're up to the challenge, remove the other assignees from the issue, leave a comment saying this task is yours, and go for it! :D

Let me know if you have any questions! ;)

![web-dev-path-github](https://user-images.githubusercontent.com/20016897/101998737-b6811b80-3c8a-11eb-8d76-a9f1bf8d8baf.png)

<hr /> 

_HOT TIP:
When submitting a Pull Request to solve an issue, mention the issue number on the PR description (not on the title) so that they both get linked.
You can use something like "Solves #26", "Referent to the issue #27", or Closes #27. By using Closes and the issue number, GitHub will automatically close the issue when the PR that is addressing it is merged into the master._

**Comment by rebecatschiedel** [comment]
I Would like to do it. :)

**Comment by MarianaSouza** [comment]
> I Would like to do it. :)

You go, girl! <3
Please, slack me if you have any questions!
