### ISSUE TITLE
Create a project description for the section About

### ISSUE THREAD

**Issue by MarianaSouza** [MarianaSouza/web-dev-path#3]
We need to create a description for the section about:

![description-about](https://user-images.githubusercontent.com/20016897/94750853-e97a6b00-033b-11eb-8203-3788e15361c2.png)

No PR needed for this task. Please just send a comment with your idea of a nice and short description (no more than two sentences) to the section ;)

Thanks!

**Comment by ZahraB21** [comment]
About
We are a team of professional women with a web development background. We aim to provide a comprehensive path for people who seek to begin their web development journey.

**Comment by MarianaSouza** [comment]
> About
> We are a team of professional women with a web development background. We aim to provide a comprehensive path for people who seek to begin their web development journey.

Love it! Thanks, @ZahraB21 ! We've got an about now :)
