### ISSUE TITLE
Fix mobile menu nav

### ISSUE THREAD

**Issue by MarianaSouza** [MarianaSouza/web-dev-path#51]
When resizing the screen to mobile, we notice that the nav items appear and disappear in an arbitrary way. Also, when clicking over the mobile hamburger menu to toggle the nav list on smaller screens, the nav items take a long time to be hidden which causes the impression they are at the top of the main page title.

Check it out on this video:
https://www.loom.com/share/b45047927b914d13a0f77a06f2e4f52d?sharedAppSource=team_library

A way to address that may be adding an `overflow: hidden;` property to the `.nav` element. That would hide the nav items completely unless we trigger the menu by activating the `.navVisible`. We can also create a simple toggle slide effect by adding a height transition to the visible nav.

![Screen Shot 2021-08-02 at 1 42 55 PM](https://user-images.githubusercontent.com/20016897/127923433-e0cc2080-66c9-491d-b459-c72eacaebccd.png)

- Branch out from the up-to-date master -> `git checkout master` ,  `git pull` and `git checkout -b fix/mobile-nav-menu`
- Apply the changes and test them thoroughly across many browsers: Chrome, Safari, Firefox, and Edge.

**Comment by manikmmalhotra** [comment]
hey @MarianaSouza , can you assign this issue to me, i wanna work on this

**Comment by MarianaSouza** [comment]
> hey @MarianaSouza , can you assign this issue to me, i wanna work on this

Hi, @manikmmalhotra ! Welcome on board! 
I've just sent you an invite to have access to our repository as a collaborator. I've also sent an invite to our Slack channel where you can get help if you have any questions. Don't hesitate to reach out!
