### ISSUE TITLE
Update Slack Link on README

### ISSUE THREAD

**Issue by MarianaSouza** [MarianaSouza/web-dev-path#58]
Our Slack invitation link added to the README is not working anymore :-/

![Screen Shot 2021-10-26 at 10 55 48 PM](https://user-images.githubusercontent.com/20016897/139008369-049351df-ea71-400b-a100-13bc224ac879.png)

After a quick research, I've found out that the invitation links expire after a month for "security reasons"
 
![Screen Shot 2021-10-25 at 10 51 49 PM](https://user-images.githubusercontent.com/20016897/139008524-d7b37f28-518c-4c4c-86b1-e63016e5bd54.png)

We need to investigate it a little further to decide if:
- there is a way to add a permanent link that will not expire.
- we're replacing that README link with [the slack channel link itself](https://webdevpath.slack.com/) followed by [this tutorial](https://slack.com/intl/en-ca/help/articles/212675257-Join-a-Slack-workspace).

_Go to your local `master` branch and run `git pull` to ensure your local project is in sync with the remote repository. Then, branch out from `master` by using `git checkout -b fix/update-slack-link` and submit a PR where this issue will be linked._

**Acceptance Criteria:**
 - Research the invitation link functionality and add your findings into your PR description.
 - Update the `README.md` file accordingly.

**Comment by Stigeriz** [comment]
@MarianaSouza I found the way to make link permanent. 
There is a setting on the Channel when you click on arrow down.
Then you can choose **Invite people to  Web Dev Path**.
After choose **Edit link setting** in that popup.
And on a new popup choose **Never expires** for **Expiration** dropdawn.
That should be it, link should never expire anymore.

**Comment by MarianaSouza** [comment]
> @MarianaSouza I found the way to make link permanent. There is a setting on the Channel when you click on arrow down. Then you can choose **Invite people to Web Dev Path**. After choose **Edit link setting** in that popup. <img alt="Screen Shot 2021-11-07 at 8 00 25 PM" width="498" src="https://user-images.githubusercontent.com/93110997/140682677-3870d3f3-aee0-4aec-8be7-a4d156ad3222.png">
> 
> And on a new popup choose **Never expires** for **Expiration** dropdawn.
> 
> <img alt="Screen Shot 2021-11-07 at 7 53 59 PM" width="498" src="https://user-images.githubusercontent.com/93110997/140682724-3ae65749-ed3d-4b38-804b-ed76f6ef1e84.png">
> 
> That should be it, link should never expire anymore.

That's awesome @Stigeriz ! Thanks for investigating it and explaining it so well with images! 👏🏼  🚀 
So, [this is the new link](https://join.slack.com/t/webdevpath/shared_invite/zt-xqqgwwo5-a09BSVWC9ZrHmS6RaMBzVw) we'll have to add to our README. Please let me know if you have any questions about how to update it. Thanks!
